version: '2'
services:
  nginx:
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
        - ./web:/site
        - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    links:
        - php7
        - es
  php7:
    build: ./php7/
    volumes:
        - ./web:/site
        - ./php7/php-ini-overrides.ini:/etc/php/fpm/conf.d/99-overrides.ini
    links:
        - db
  db:
    image: mariadb
    restart: always
    volumes:
        - ./bdd:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=radinard
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2
    volumes:
      - ./provision:/provision
    